# Generated by Django 2.2.7 on 2020-05-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0022_account_administrator_advertiser_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('slogan', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('Advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Advertiser')),
            ],
        ),
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_photo', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('rating', models.IntegerField(default=0)),
                ('length', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('status', models.CharField(default='none', max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(default='none', max_length=100)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboards.Billboard')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.Account')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billboards.Advertisement')),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboards.Billboard')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboards.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(default='none', max_length=100)),
                ('body', models.CharField(default='none', max_length=100)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='accounts.Account')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
