# Generated by Django 2.2.7 on 2020-10-18 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_account_account'),
        ('billboards', '0002_auto_20201001_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='advertiser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Advertiser'),
        ),
    ]
