# Generated by Django 2.2.7 on 2019-12-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191218_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboard',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='billboard',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='billboard',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='billboard',
            name='photo4',
        ),
    ]
