# Generated by Django 2.2.7 on 2019-12-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191218_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
