# Generated by Django 2.2.7 on 2020-01-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_billboard_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='billboard',
            name='length',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='billboard',
            name='width',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
