# Generated by Django 2.2.7 on 2020-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200103_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilePicture',
            field=models.ImageField(upload_to='profile pictures'),
        ),
    ]
