# Generated by Django 2.2.7 on 2020-01-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200103_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='Owner',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='profilePicture',
            field=models.ImageField(default=None, upload_to='profile pictures'),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='location',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
