# Generated by Django 2.2.7 on 2020-01-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200103_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='photo1',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='billboard',
            name='photo2',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='billboard',
            name='photo3',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='billboard',
            name='photo4',
            field=models.IntegerField(default=None),
        ),
    ]
