# Generated by Django 2.2.7 on 2020-01-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_account_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Billboard',
        ),
    ]
