# Generated by Django 2.2.7 on 2020-04-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_account_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Adminstrator',
        ),
        migrations.DeleteModel(
            name='Advertiser',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
